### PR TITLE
upgrade to 0.18.0 release

### PR DESCRIPTION
**Pull request by groob**
I tried to update the module for the upcoming 0.18 release. 
It appears that `Json.customDecoder` was removed, and got stuck. Would you mind taking a look? 

I believe everything else works.

### CODE REVIEW

**Comment by groob** [comment]
I found a solution on the forums. The Demo pages work with 0.18 now.

**Comment by gregziegan** [comment]
Hey! thanks so much!

Could you actually make this PR for [elm-menu](https://github.com/thebritican/elm-menu)?

I'm working today on introducing an API that's more drop in. But the current API that you just updated to `0.18` will be available in `elm-menu` 😄

**Comment by gregziegan** [comment]
To clarify, `elm-menu` will be a dependency of `elm-autocomplete` and `elm-autocomplete` will become the `AccessibleExample` without subscriptions

**Comment by gregziegan** [comment]
actually, decided to merge this and release so people can work with the existing API while I work on the new one! Thanks for the contribution!

**Pull request merged**
