### PR TITLE
New API

### PR DESCRIPTION
**Pull request by gregziegan**
Implementation of all the notes from #26 

You can see what brought me to this API from [this video](https://www.youtube.com/watch?v=KSuCYUqY058)
### TODO:
- [x] API that allows the consumer to own the data
- [x] Support keydowns via subscription
- [x] Support sections
- [x] Allow for a single selection state (mouse & key unified)
- [x] Fix tests
- [x] Documentation

### CODE REVIEW

**Comment by maximsch2** [comment]
Really excited to move to the new API. Out of curiosity: why did you require a new native module for a simple map function? Is it just a way to force-convert the type?

**Comment by gregziegan** [comment]
Correct! Talked w/ Evan about the strategy to get this published sooner than later. `Attribute.map` will be coming in the next release, so the native module is just an intermediary trick.

Won't have much time to merge and clean this up until the weekend. But also looking into subscriptions for menu only key events, may remove the input depending on the success of the subscriptions, and finally: menu sections like seen in [react autosuggest](http://react-autosuggest.js.org/).

I will also default as many attributes as possible to default WAI-ARIA compliance and do some screen reader testing.

**Comment by gregziegan** [comment]
Tests are currently not useful: Having a silent error on import. Looking into getting an [sscce](http://sscce.org/) for `elm-test`. Not going to block a release on tests, though.

**Comment by gregziegan** [comment]
Just got whitelisted
https://github.com/elm-lang/package.elm-lang.org/pull/199

So of course i'm going to wreak havoc with runtime errors 😈 

Working on documentation now and want to have a WAI-ARIA support example, since I don't provide an input. I want to see when making that example if there's a way to provide a convenience function.

**Comment by gregziegan** [comment]
PR is getting too old, will make small PRs for the last points addressing issues directly

**Pull request merged**
